title: Stortford Strollers Walking Basketball Club
url: "https://stortfordstrollers.com"
baseurl: "/"

permalink: /:categories/:year-:month-:day.html

subsume: https://api.subsume.io/

exclude: ['CNAME', '*.sublime-*']
