title: Stortford Strollers Walking Basketball Club
url: "https://stortfordstrollers"
baseurl: "/"

collections:
  matchreports:
    output: true

subsume: https://api.subsume.io/

exclude: ['CNAME', '*.sublime-*']
