title: Stortford Strollers Walking Basketball Club
url: "http://localhost:4000" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog/

permalink: /:categories/:year-:month-:day.html

subsume: http://api.subsume.dev/
